# Generated by Django 2.0.6 on 2019-01-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startFundraiser', '0016_merge_20181212_0047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqs',
            options={'verbose_name_plural': 'faqs'},
        ),
    ]
